# Generated by Django 5.0.14 on 2026-04-19 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_label', models.CharField(help_text='e.g. August 5, 2026', max_length=60)),
                ('day', models.CharField(help_text='e.g. 05', max_length=4)),
                ('month', models.CharField(help_text='e.g. Aug', max_length=12)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Swarved Mahamandir, Umraha, Varanasi', max_length=200)),
                ('time_label', models.CharField(default='All Day', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('image_path', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/')),
                ('cover_path', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(help_text='Small text above title', max_length=200)),
                ('title_sanskrit', models.CharField(blank=True, help_text='Devanagari title', max_length=200)),
                ('title_english', models.CharField(help_text='English title', max_length=200)),
                ('subtitle', models.TextField(help_text='Paragraph under the title')),
                ('cta_primary_label', models.CharField(default='Enter the Mahamandir', max_length=60)),
                ('cta_primary_url', models.CharField(default='/mahamandir/', max_length=200)),
                ('cta_secondary_label', models.CharField(blank=True, default='The Swarved', max_length=60)),
                ('cta_secondary_url', models.CharField(blank=True, default='/about/', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_path', models.CharField(blank=True, help_text='Static path if no image uploaded (e.g. img/mahamandir/temple-night.jpg)', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('temple', '🛕 Temple'), ('book', '📖 Book'), ('dove', '🕊️ Dove'), ('lotus', '🪷 Lotus'), ('leaf', '🌿 Leaf'), ('hands', '🤝 Hands'), ('eye', '👁️ Eye'), ('fire', '🔥 Fire'), ('meditation', '🧘 Meditation'), ('satsang', '🕉️ Satsang'), ('darshan', '🪔 Darshan'), ('seva', '🤲 Seva'), ('heart', '❤️ Heart'), ('drop', '🩸 Drop')], default='meditation', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(choices=[('temple', '🛕 Temple'), ('book', '📖 Book'), ('dove', '🕊️ Dove'), ('lotus', '🪷 Lotus'), ('leaf', '🌿 Leaf'), ('hands', '🤝 Hands'), ('eye', '👁️ Eye'), ('fire', '🔥 Fire'), ('meditation', '🧘 Meditation'), ('satsang', '🕉️ Satsang'), ('darshan', '🪔 Darshan'), ('seva', '🤲 Seva'), ('heart', '❤️ Heart'), ('drop', '🩸 Drop')], default='lotus', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('short_text', models.CharField(max_length=300)),
                ('long_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_path', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Swarved Mahamandir', max_length=120)),
                ('tagline', models.CharField(default='Enlightenment Enshrined', max_length=200)),
                ('address', models.CharField(default='Swarved Mahamandir, Umraha, Varanasi, Uttar Pradesh, India', max_length=300)),
                ('phone', models.CharField(default='+91 8586808820', max_length=40)),
                ('email', models.EmailField(default='pradhan.karyalay@gmail.com', max_length=254)),
                ('email_alt', models.EmailField(blank=True, default='swarvedmahamandirtrust@gmail.com', max_length=254)),
                ('donate_url', models.URLField(blank=True, default='https://donate.swarved-mahamandir.org/')),
                ('hours_summer', models.CharField(default='8:00 AM – 9:00 PM', max_length=60)),
                ('hours_winter', models.CharField(default='8:00 AM – 8:00 PM', max_length=60)),
                ('darshan_morning', models.CharField(default='4:00 AM – 6:00 AM', max_length=60)),
                ('darshan_evening', models.CharField(default='6:00 PM – 8:00 PM', max_length=60)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/swarved.mahamandir/')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/swarved_mahamandir_dham_/')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 3,137 or 20,000+', max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/photos/')),
                ('image_path', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallerycategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
