# Generated by Django 5.0.14 on 2026-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_gallerycategory_heroslide_offering_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g. home.about_intro — do not change after creation', max_length=120, unique=True)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About / The Swarved'), ('mahamandir', 'The Mandir'), ('services', 'Initiatives'), ('gallery', 'Gallery'), ('events', 'Events'), ('donate', 'Donate'), ('contact', 'Contact')], default='home', max_length=20)),
                ('label', models.CharField(help_text='Human name shown in the admin (e.g. "About intro section")', max_length=160)),
                ('kicker', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('subtitle', models.TextField(blank=True, help_text='Optional lede / short paragraph under the title')),
                ('body', models.TextField(blank=True, help_text='Main paragraphs — separate with a blank line for multiple paragraphs')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/')),
                ('image_path', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('quote', models.TextField(blank=True, help_text='Optional inline pull-quote')),
                ('quote_cite', models.CharField(blank=True, max_length=200)),
                ('draft_data', models.JSONField(blank=True, help_text='Unpublished edits. Empty = no pending changes.', null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'order', 'id'],
            },
        ),
    ]
